// Generated by using Rcpp::compileAttributes() -> do not edit by hand
// Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

#include "../inst/include/rsk.h"
#include <RcppArmadillo.h>
#include <Rcpp.h>
#include <string>
#include <set>

using namespace Rcpp;

// anti_subset
arma::mat anti_subset(arma::vec& x, arma::uvec& idx, arma::uword nc, arma::uword nr);
static SEXP _rsk_anti_subset_try(SEXP xSEXP, SEXP idxSEXP, SEXP ncSEXP, SEXP nrSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::traits::input_parameter< arma::vec& >::type x(xSEXP);
    Rcpp::traits::input_parameter< arma::uvec& >::type idx(idxSEXP);
    Rcpp::traits::input_parameter< arma::uword >::type nc(ncSEXP);
    Rcpp::traits::input_parameter< arma::uword >::type nr(nrSEXP);
    rcpp_result_gen = Rcpp::wrap(anti_subset(x, idx, nc, nr));
    return rcpp_result_gen;
END_RCPP_RETURN_ERROR
}
RcppExport SEXP _rsk_anti_subset(SEXP xSEXP, SEXP idxSEXP, SEXP ncSEXP, SEXP nrSEXP) {
    SEXP rcpp_result_gen;
    {
        Rcpp::RNGScope rcpp_rngScope_gen;
        rcpp_result_gen = PROTECT(_rsk_anti_subset_try(xSEXP, idxSEXP, ncSEXP, nrSEXP));
    }
    Rboolean rcpp_isInterrupt_gen = Rf_inherits(rcpp_result_gen, "interrupted-error");
    if (rcpp_isInterrupt_gen) {
        UNPROTECT(1);
        Rf_onintr();
    }
    bool rcpp_isLongjump_gen = Rcpp::internal::isLongjumpSentinel(rcpp_result_gen);
    if (rcpp_isLongjump_gen) {
        Rcpp::internal::resumeJump(rcpp_result_gen);
    }
    Rboolean rcpp_isError_gen = Rf_inherits(rcpp_result_gen, "try-error");
    if (rcpp_isError_gen) {
        SEXP rcpp_msgSEXP_gen = Rf_asChar(rcpp_result_gen);
        UNPROTECT(1);
        Rf_error(CHAR(rcpp_msgSEXP_gen));
    }
    UNPROTECT(1);
    return rcpp_result_gen;
}
// rbr_times
Rcpp::DatetimeVector rbr_times(const arma::vec& ev_tstamp, const arma::uvec& ev_index, double ti);
static SEXP _rsk_rbr_times_try(SEXP ev_tstampSEXP, SEXP ev_indexSEXP, SEXP tiSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::traits::input_parameter< const arma::vec& >::type ev_tstamp(ev_tstampSEXP);
    Rcpp::traits::input_parameter< const arma::uvec& >::type ev_index(ev_indexSEXP);
    Rcpp::traits::input_parameter< double >::type ti(tiSEXP);
    rcpp_result_gen = Rcpp::wrap(rbr_times(ev_tstamp, ev_index, ti));
    return rcpp_result_gen;
END_RCPP_RETURN_ERROR
}
RcppExport SEXP _rsk_rbr_times(SEXP ev_tstampSEXP, SEXP ev_indexSEXP, SEXP tiSEXP) {
    SEXP rcpp_result_gen;
    {
        Rcpp::RNGScope rcpp_rngScope_gen;
        rcpp_result_gen = PROTECT(_rsk_rbr_times_try(ev_tstampSEXP, ev_indexSEXP, tiSEXP));
    }
    Rboolean rcpp_isInterrupt_gen = Rf_inherits(rcpp_result_gen, "interrupted-error");
    if (rcpp_isInterrupt_gen) {
        UNPROTECT(1);
        Rf_onintr();
    }
    bool rcpp_isLongjump_gen = Rcpp::internal::isLongjumpSentinel(rcpp_result_gen);
    if (rcpp_isLongjump_gen) {
        Rcpp::internal::resumeJump(rcpp_result_gen);
    }
    Rboolean rcpp_isError_gen = Rf_inherits(rcpp_result_gen, "try-error");
    if (rcpp_isError_gen) {
        SEXP rcpp_msgSEXP_gen = Rf_asChar(rcpp_result_gen);
        UNPROTECT(1);
        Rf_error(CHAR(rcpp_msgSEXP_gen));
    }
    UNPROTECT(1);
    return rcpp_result_gen;
}
// rbr_raw_to_pressure
arma::vec rbr_raw_to_pressure(const arma::vec& x, const arma::vec& calib);
static SEXP _rsk_rbr_raw_to_pressure_try(SEXP xSEXP, SEXP calibSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::traits::input_parameter< const arma::vec& >::type x(xSEXP);
    Rcpp::traits::input_parameter< const arma::vec& >::type calib(calibSEXP);
    rcpp_result_gen = Rcpp::wrap(rbr_raw_to_pressure(x, calib));
    return rcpp_result_gen;
END_RCPP_RETURN_ERROR
}
RcppExport SEXP _rsk_rbr_raw_to_pressure(SEXP xSEXP, SEXP calibSEXP) {
    SEXP rcpp_result_gen;
    {
        Rcpp::RNGScope rcpp_rngScope_gen;
        rcpp_result_gen = PROTECT(_rsk_rbr_raw_to_pressure_try(xSEXP, calibSEXP));
    }
    Rboolean rcpp_isInterrupt_gen = Rf_inherits(rcpp_result_gen, "interrupted-error");
    if (rcpp_isInterrupt_gen) {
        UNPROTECT(1);
        Rf_onintr();
    }
    bool rcpp_isLongjump_gen = Rcpp::internal::isLongjumpSentinel(rcpp_result_gen);
    if (rcpp_isLongjump_gen) {
        Rcpp::internal::resumeJump(rcpp_result_gen);
    }
    Rboolean rcpp_isError_gen = Rf_inherits(rcpp_result_gen, "try-error");
    if (rcpp_isError_gen) {
        SEXP rcpp_msgSEXP_gen = Rf_asChar(rcpp_result_gen);
        UNPROTECT(1);
        Rf_error(CHAR(rcpp_msgSEXP_gen));
    }
    UNPROTECT(1);
    return rcpp_result_gen;
}
// rbr_raw_to_temperature
arma::vec rbr_raw_to_temperature(const arma::vec& x, const arma::vec& calib);
static SEXP _rsk_rbr_raw_to_temperature_try(SEXP xSEXP, SEXP calibSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::traits::input_parameter< const arma::vec& >::type x(xSEXP);
    Rcpp::traits::input_parameter< const arma::vec& >::type calib(calibSEXP);
    rcpp_result_gen = Rcpp::wrap(rbr_raw_to_temperature(x, calib));
    return rcpp_result_gen;
END_RCPP_RETURN_ERROR
}
RcppExport SEXP _rsk_rbr_raw_to_temperature(SEXP xSEXP, SEXP calibSEXP) {
    SEXP rcpp_result_gen;
    {
        Rcpp::RNGScope rcpp_rngScope_gen;
        rcpp_result_gen = PROTECT(_rsk_rbr_raw_to_temperature_try(xSEXP, calibSEXP));
    }
    Rboolean rcpp_isInterrupt_gen = Rf_inherits(rcpp_result_gen, "interrupted-error");
    if (rcpp_isInterrupt_gen) {
        UNPROTECT(1);
        Rf_onintr();
    }
    bool rcpp_isLongjump_gen = Rcpp::internal::isLongjumpSentinel(rcpp_result_gen);
    if (rcpp_isLongjump_gen) {
        Rcpp::internal::resumeJump(rcpp_result_gen);
    }
    Rboolean rcpp_isError_gen = Rf_inherits(rcpp_result_gen, "try-error");
    if (rcpp_isError_gen) {
        SEXP rcpp_msgSEXP_gen = Rf_asChar(rcpp_result_gen);
        UNPROTECT(1);
        Rf_error(CHAR(rcpp_msgSEXP_gen));
    }
    UNPROTECT(1);
    return rcpp_result_gen;
}
// rbr_temperature_correction
arma::vec rbr_temperature_correction(const arma::vec& pressure, const arma::vec& temperature, const arma::vec& x);
static SEXP _rsk_rbr_temperature_correction_try(SEXP pressureSEXP, SEXP temperatureSEXP, SEXP xSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::traits::input_parameter< const arma::vec& >::type pressure(pressureSEXP);
    Rcpp::traits::input_parameter< const arma::vec& >::type temperature(temperatureSEXP);
    Rcpp::traits::input_parameter< const arma::vec& >::type x(xSEXP);
    rcpp_result_gen = Rcpp::wrap(rbr_temperature_correction(pressure, temperature, x));
    return rcpp_result_gen;
END_RCPP_RETURN_ERROR
}
RcppExport SEXP _rsk_rbr_temperature_correction(SEXP pressureSEXP, SEXP temperatureSEXP, SEXP xSEXP) {
    SEXP rcpp_result_gen;
    {
        Rcpp::RNGScope rcpp_rngScope_gen;
        rcpp_result_gen = PROTECT(_rsk_rbr_temperature_correction_try(pressureSEXP, temperatureSEXP, xSEXP));
    }
    Rboolean rcpp_isInterrupt_gen = Rf_inherits(rcpp_result_gen, "interrupted-error");
    if (rcpp_isInterrupt_gen) {
        UNPROTECT(1);
        Rf_onintr();
    }
    bool rcpp_isLongjump_gen = Rcpp::internal::isLongjumpSentinel(rcpp_result_gen);
    if (rcpp_isLongjump_gen) {
        Rcpp::internal::resumeJump(rcpp_result_gen);
    }
    Rboolean rcpp_isError_gen = Rf_inherits(rcpp_result_gen, "try-error");
    if (rcpp_isError_gen) {
        SEXP rcpp_msgSEXP_gen = Rf_asChar(rcpp_result_gen);
        UNPROTECT(1);
        Rf_error(CHAR(rcpp_msgSEXP_gen));
    }
    UNPROTECT(1);
    return rcpp_result_gen;
}
// test_all
Rcpp::DataFrame test_all(arma::vec& raw_vector, arma::uvec idx, size_t nc, const arma::vec& ev_tstamp, const arma::uvec& ev_index, double ti, const arma::mat& base_calib, const arma::vec& is_temp, const arma::vec& temp_comp, size_t pres_index, size_t temp_index, Rcpp::CharacterVector names, int subset);
static SEXP _rsk_test_all_try(SEXP raw_vectorSEXP, SEXP idxSEXP, SEXP ncSEXP, SEXP ev_tstampSEXP, SEXP ev_indexSEXP, SEXP tiSEXP, SEXP base_calibSEXP, SEXP is_tempSEXP, SEXP temp_compSEXP, SEXP pres_indexSEXP, SEXP temp_indexSEXP, SEXP namesSEXP, SEXP subsetSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::traits::input_parameter< arma::vec& >::type raw_vector(raw_vectorSEXP);
    Rcpp::traits::input_parameter< arma::uvec >::type idx(idxSEXP);
    Rcpp::traits::input_parameter< size_t >::type nc(ncSEXP);
    Rcpp::traits::input_parameter< const arma::vec& >::type ev_tstamp(ev_tstampSEXP);
    Rcpp::traits::input_parameter< const arma::uvec& >::type ev_index(ev_indexSEXP);
    Rcpp::traits::input_parameter< double >::type ti(tiSEXP);
    Rcpp::traits::input_parameter< const arma::mat& >::type base_calib(base_calibSEXP);
    Rcpp::traits::input_parameter< const arma::vec& >::type is_temp(is_tempSEXP);
    Rcpp::traits::input_parameter< const arma::vec& >::type temp_comp(temp_compSEXP);
    Rcpp::traits::input_parameter< size_t >::type pres_index(pres_indexSEXP);
    Rcpp::traits::input_parameter< size_t >::type temp_index(temp_indexSEXP);
    Rcpp::traits::input_parameter< Rcpp::CharacterVector >::type names(namesSEXP);
    Rcpp::traits::input_parameter< int >::type subset(subsetSEXP);
    rcpp_result_gen = Rcpp::wrap(test_all(raw_vector, idx, nc, ev_tstamp, ev_index, ti, base_calib, is_temp, temp_comp, pres_index, temp_index, names, subset));
    return rcpp_result_gen;
END_RCPP_RETURN_ERROR
}
RcppExport SEXP _rsk_test_all(SEXP raw_vectorSEXP, SEXP idxSEXP, SEXP ncSEXP, SEXP ev_tstampSEXP, SEXP ev_indexSEXP, SEXP tiSEXP, SEXP base_calibSEXP, SEXP is_tempSEXP, SEXP temp_compSEXP, SEXP pres_indexSEXP, SEXP temp_indexSEXP, SEXP namesSEXP, SEXP subsetSEXP) {
    SEXP rcpp_result_gen;
    {
        Rcpp::RNGScope rcpp_rngScope_gen;
        rcpp_result_gen = PROTECT(_rsk_test_all_try(raw_vectorSEXP, idxSEXP, ncSEXP, ev_tstampSEXP, ev_indexSEXP, tiSEXP, base_calibSEXP, is_tempSEXP, temp_compSEXP, pres_indexSEXP, temp_indexSEXP, namesSEXP, subsetSEXP));
    }
    Rboolean rcpp_isInterrupt_gen = Rf_inherits(rcpp_result_gen, "interrupted-error");
    if (rcpp_isInterrupt_gen) {
        UNPROTECT(1);
        Rf_onintr();
    }
    bool rcpp_isLongjump_gen = Rcpp::internal::isLongjumpSentinel(rcpp_result_gen);
    if (rcpp_isLongjump_gen) {
        Rcpp::internal::resumeJump(rcpp_result_gen);
    }
    Rboolean rcpp_isError_gen = Rf_inherits(rcpp_result_gen, "try-error");
    if (rcpp_isError_gen) {
        SEXP rcpp_msgSEXP_gen = Rf_asChar(rcpp_result_gen);
        UNPROTECT(1);
        Rf_error(CHAR(rcpp_msgSEXP_gen));
    }
    UNPROTECT(1);
    return rcpp_result_gen;
}

// validate (ensure exported C++ functions exist before calling them)
static int _rsk_RcppExport_validate(const char* sig) { 
    static std::set<std::string> signatures;
    if (signatures.empty()) {
        signatures.insert("arma::mat(*anti_subset)(arma::vec&,arma::uvec&,arma::uword,arma::uword)");
        signatures.insert("Rcpp::DatetimeVector(*rbr_times)(const arma::vec&,const arma::uvec&,double)");
        signatures.insert("arma::vec(*rbr_raw_to_pressure)(const arma::vec&,const arma::vec&)");
        signatures.insert("arma::vec(*rbr_raw_to_temperature)(const arma::vec&,const arma::vec&)");
        signatures.insert("arma::vec(*rbr_temperature_correction)(const arma::vec&,const arma::vec&,const arma::vec&)");
        signatures.insert("Rcpp::DataFrame(*test_all)(arma::vec&,arma::uvec,size_t,const arma::vec&,const arma::uvec&,double,const arma::mat&,const arma::vec&,const arma::vec&,size_t,size_t,Rcpp::CharacterVector,int)");
    }
    return signatures.find(sig) != signatures.end();
}

// registerCCallable (register entry points for exported C++ functions)
RcppExport SEXP _rsk_RcppExport_registerCCallable() { 
    R_RegisterCCallable("rsk", "_rsk_anti_subset", (DL_FUNC)_rsk_anti_subset_try);
    R_RegisterCCallable("rsk", "_rsk_rbr_times", (DL_FUNC)_rsk_rbr_times_try);
    R_RegisterCCallable("rsk", "_rsk_rbr_raw_to_pressure", (DL_FUNC)_rsk_rbr_raw_to_pressure_try);
    R_RegisterCCallable("rsk", "_rsk_rbr_raw_to_temperature", (DL_FUNC)_rsk_rbr_raw_to_temperature_try);
    R_RegisterCCallable("rsk", "_rsk_rbr_temperature_correction", (DL_FUNC)_rsk_rbr_temperature_correction_try);
    R_RegisterCCallable("rsk", "_rsk_test_all", (DL_FUNC)_rsk_test_all_try);
    R_RegisterCCallable("rsk", "_rsk_RcppExport_validate", (DL_FUNC)_rsk_RcppExport_validate);
    return R_NilValue;
}

static const R_CallMethodDef CallEntries[] = {
    {"_rsk_anti_subset", (DL_FUNC) &_rsk_anti_subset, 4},
    {"_rsk_rbr_times", (DL_FUNC) &_rsk_rbr_times, 3},
    {"_rsk_rbr_raw_to_pressure", (DL_FUNC) &_rsk_rbr_raw_to_pressure, 2},
    {"_rsk_rbr_raw_to_temperature", (DL_FUNC) &_rsk_rbr_raw_to_temperature, 2},
    {"_rsk_rbr_temperature_correction", (DL_FUNC) &_rsk_rbr_temperature_correction, 3},
    {"_rsk_test_all", (DL_FUNC) &_rsk_test_all, 13},
    {"_rsk_RcppExport_registerCCallable", (DL_FUNC) &_rsk_RcppExport_registerCCallable, 0},
    {NULL, NULL, 0}
};

RcppExport void R_init_rsk(DllInfo *dll) {
    R_registerRoutines(dll, NULL, CallEntries, NULL, NULL);
    R_useDynamicSymbols(dll, FALSE);
}
