# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

#' @title rsk_raw_to_pressure
NULL

#' @title rsk_raw_to_temperature
NULL

#' @title rsk_temperature_correction
NULL

#' @title rsk_raw_times
NULL

raw_to_4byte_unsigned <- function(x) {
    .Call('_rsk_raw_to_4byte_unsigned', PACKAGE = 'rsk', x)
}

raw_to_4byte_signed <- function(x, index) {
    .Call('_rsk_raw_to_4byte_signed', PACKAGE = 'rsk', x, index)
}

raw_to_unsigned_vec <- function(x, header_length, n_columns, to_remove) {
    .Call('_rsk_raw_to_unsigned_vec', PACKAGE = 'rsk', x, header_length, n_columns, to_remove)
}

rsk_find_events <- function(x, header_length) {
    .Call('_rsk_rsk_find_events', PACKAGE = 'rsk', x, header_length)
}

rsk_incomplete_events <- function(x, times, n_cols, f5) {
    .Call('_rsk_rsk_incomplete_events', PACKAGE = 'rsk', x, times, n_cols, f5)
}

rsk_raw_to_pressure <- function(x, calib) {
    .Call('_rsk_rsk_raw_to_pressure', PACKAGE = 'rsk', x, calib)
}

rsk_raw_to_temperature <- function(x, calib) {
    .Call('_rsk_rsk_raw_to_temperature', PACKAGE = 'rsk', x, calib)
}

rsk_temperature_correction <- function(out, tcal, x) {
    .Call('_rsk_rsk_temperature_correction', PACKAGE = 'rsk', out, tcal, x)
}

rsk_raw_times <- function(raw_tstamp, raw_index, n_times, n_columns, measurement_interval) {
    .Call('_rsk_rsk_raw_times', PACKAGE = 'rsk', raw_tstamp, raw_index, n_times, n_columns, measurement_interval)
}

get_header_length <- function(x) {
    .Call('_rsk_get_header_length', PACKAGE = 'rsk', x)
}

rsk_read_bin <- function(x, is_temp, base_calib, temp_comp, measurement_interval, pressure_index, temperature_index, keep_raw) {
    .Call('_rsk_rsk_read_bin', PACKAGE = 'rsk', x, is_temp, base_calib, temp_comp, measurement_interval, pressure_index, temperature_index, keep_raw)
}

# Register entry points for exported C++ functions
methods::setLoadAction(function(ns) {
    .Call('_rsk_RcppExport_registerCCallable', PACKAGE = 'rsk')
})
