# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

anti_subset <- function(x, idx, nc, nr) {
    .Call('_rsk_anti_subset', PACKAGE = 'rsk', x, idx, nc, nr)
}

#' rbr_times
#'
#' @param ev_tstamp
#' @param ev_index
#' @param ti
#'
#' @return
#' @export
#'
#' @examples
rbr_times <- function(ev_tstamp, ev_index, ti) {
    .Call('_rsk_rbr_times', PACKAGE = 'rsk', ev_tstamp, ev_index, ti)
}

#' rbr_raw_to_pressure
#'
#' @param x
#' @param calib
#'
#' @return
#' @export
#'
#' @examples
rbr_raw_to_pressure <- function(x, calib) {
    .Call('_rsk_rbr_raw_to_pressure', PACKAGE = 'rsk', x, calib)
}

#' rbr_raw_to_temperature
#'
#' @param x
#' @param calib
#'
#' @return
#' @export
#'
#' @examples
rbr_raw_to_temperature <- function(x, calib) {
    .Call('_rsk_rbr_raw_to_temperature', PACKAGE = 'rsk', x, calib)
}

#' rbr_temperature_correction
#'
#' @param pressure
#' @param temperature
#' @param x calibration constants
#'
#' @return
#' @export
#'
#' @examples
rbr_temperature_correction <- function(pressure, temperature, x) {
    .Call('_rsk_rbr_temperature_correction', PACKAGE = 'rsk', pressure, temperature, x)
}

test_all <- function(raw_vector, idx, nc, ev_tstamp, ev_index, ti, base_calib, is_temp, temp_comp, pres_index, temp_index, names, subset = 1L) {
    .Call('_rsk_test_all', PACKAGE = 'rsk', raw_vector, idx, nc, ev_tstamp, ev_index, ti, base_calib, is_temp, temp_comp, pres_index, temp_index, names, subset)
}

# Register entry points for exported C++ functions
methods::setLoadAction(function(ns) {
    .Call('_rsk_RcppExport_registerCCallable', PACKAGE = 'rsk')
})
